package org.hertsstack.codegen;

import java.io.FileWriter;
import java.io.IOException;

class CodeGenUtil {
    public static final String GEN_COMMENT = "// Don't edit this file because this file is generated by herts codegen.";

    public static String capitalizeFirstLetter(String input) {
        if (input == null || input.isEmpty()) {
            return input;
        }

        char firstChar = input.charAt(0);
        if (Character.isLowerCase(firstChar)) {
            firstChar = Character.toUpperCase(firstChar);
            return firstChar + input.substring(1);
        } else {
            return input;
        }
    }

    private static boolean isInheritHertsMessage(String className) {
        if (className == null) {
            return false;
        }
        return className.contains("HertsMessage");
    }

    public static boolean isCustomModelClass(Class<?> classInfo) {
        if (classInfo.getSuperclass() != null && isInheritHertsMessage(classInfo.getSuperclass().getName())) {
            return true;
        }
        return false;
    }

    public static void writeFile(String fileName, String rawData) {
        try {
            FileWriter fw = new FileWriter(fileName, false);
            fw.write(rawData);
            fw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}
