"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpCodegenTestServiceClient = void 0;
// Don't edit this file because this file is generated by herts codegen.
var axios_1 = require("axios");
var HttpCodegenTestServiceClient = /** @class */ (function () {
    /**
     * API endpoint information with protocol schema.
     * @param apiSchema http|https://hoge.com
     */
    function HttpCodegenTestServiceClient(apiSchema) {
        this.apiSchema = apiSchema;
    }
    HttpCodegenTestServiceClient.prototype.integerFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/integerFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_integerFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/integerFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.doubleClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/doubleClassFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_doubleClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/doubleClassFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.byteClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/byteClassFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_byteClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/byteClassFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.shortClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/shortClassFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_shortClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/shortClassFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.longClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/longClassFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_longClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/longClassFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.floatClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/floatClassFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_floatClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/floatClassFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.booleanClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/booleanClassFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_booleanClassFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/booleanClassFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.booleanFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/booleanFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_booleanFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/booleanFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.characterFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/characterFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_characterFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/characterFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.bigDecimalFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/bigDecimalFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_bigDecimalFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/bigDecimalFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.listStrFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/listStrFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_listStrFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/listStrFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.customModelFunc = function (headers, body) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/customModelFunc"), body, {
                            headers: headers,
                        })
                            .then(function (res) {
                            if (res.data.payload === undefined || res.data.payload === null) {
                                return null;
                            }
                            return res.data.payload.value;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_customModelFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/customModelFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.arrayListFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/arrayListFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_arrayListFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/arrayListFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.customModelListFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/customModelListFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_customModelListFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/customModelListFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.hashMapFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/hashMapFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_hashMapFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/hashMapFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.customModelMapFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/customModelMapFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_customModelMapFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/customModelMapFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.stringFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/stringFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_stringFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/stringFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.intFunc = function (headers, body) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/intFunc"), body, {
                            headers: headers,
                        })
                            .then(function (res) {
                            if (res.data.payload === undefined || res.data.payload === null) {
                                return null;
                            }
                            return res.data.payload.value;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_intFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/intFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.doubleFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/doubleFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_doubleFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/doubleFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.byteFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/byteFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_byteFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/byteFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.shortFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/shortFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_shortFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/shortFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.lingFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/lingFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_lingFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/lingFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.floatFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/floatFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_floatFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/floatFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.charFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/charFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_charFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/charFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.bigIntFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/bigIntFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_bigIntFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/bigIntFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.dateFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/dateFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_dateFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/dateFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.uuidFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/uuidFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_uuidFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/uuidFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.mapStrFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/mapStrFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_mapStrFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/mapStrFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.voidFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/voidFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_voidFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/voidFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.arrayFunc = function (headers, body) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/arrayFunc"), body, {
                            headers: headers,
                        })
                            .then(function (res) {
                            if (res.data.payload === undefined || res.data.payload === null) {
                                return null;
                            }
                            return res.data.payload.value;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_arrayFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/arrayFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.listFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/listFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_listFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/listFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.mapFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/mapFunc"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_mapFunc = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/mapFunc"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.createUser = function (headers, body) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/createUser"), body, {
                            headers: headers,
                        })
                            .then(function (res) {
                            if (res.data.payload === undefined || res.data.payload === null) {
                                return null;
                            }
                            return res.data.payload.value;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_createUser = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/createUser"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.getUsers = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            var body;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        body = null;
                        return [4 /*yield*/, axios_1.default.post("".concat((this.apiSchema), "/api/HttpCodegenTestService/getUsers"), body, {
                                headers: headers,
                            })
                                .then(function (res) {
                                if (res.data.payload === undefined || res.data.payload === null) {
                                    return null;
                                }
                                return res.data.payload.value;
                            })
                                .catch(function (e) {
                                throw e;
                            })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    HttpCodegenTestServiceClient.prototype.options_getUsers = function (headers) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4 /*yield*/, axios_1.default.options("".concat((this.apiSchema), "/api/HttpCodegenTestService/getUsers"), {
                            headers: headers
                        })
                            .then(function (res) {
                            return res.headers;
                        })
                            .catch(function (e) {
                            throw e;
                        })];
                    case 1: return [2 /*return*/, _a.sent()];
                }
            });
        });
    };
    return HttpCodegenTestServiceClient;
}());
exports.HttpCodegenTestServiceClient = HttpCodegenTestServiceClient;
