// Don't edit this file because this file is generated by herts codegen.
export type RequestHeaders = {
	[x: string]: string | number | boolean;
}

export class CustomModel {
    constructor(
        id : number,
        data : string,
        nestedCustomModel : NestedCustomModel,
    ) {
        this.id = id
        this.data = data
        this.nestedCustomModel = nestedCustomModel
    }
    id : number
    data : string
    nestedCustomModel : NestedCustomModel
}
export class NestedCustomModel {
    constructor(
        nestedId : number,
        pointer : string,
    ) {
        this.nestedId = nestedId
        this.pointer = pointer
    }
    nestedId : number
    pointer : string
}
export class User {
    constructor(
        id : string,
        name : string,
        createdAt : Date,
    ) {
        this.id = id
        this.name = name
        this.createdAt = createdAt
    }
    id : string
    name : string
    createdAt : Date
}


export class TestModel {
    constructor(
        id : string,
        name : string,
    ) {
        this.id = id
        this.name = name
    }
    id : string
    name : string
}

