name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  end-2-end:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java11'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'End 2 End test with Java11'
        shell: bash
        run: |
          gradle wrapper
          ./e2e-test/test.sh 11

  build-java17:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java17'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Build Herts project with Java17'
        run: |
          gradle wrapper
          ./gradlew clean build -P javaVersion=17
          cat herts-core/build/tmp/jar/MANIFEST.MF

  build-java16:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java16'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '16'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Build Herts project with Java16'
        run: |
          gradle wrapper
          ./gradlew clean build -P javaVersion=16
          cat herts-core/build/tmp/jar/MANIFEST.MF

  build-java11:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java11'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Build Herts project with Java11'
        run: |
          gradle wrapper
          ./gradlew clean build -x herts-codegen -P javaVersion=11
          cat herts-core/build/tmp/jar/MANIFEST.MF
