name: 'Build'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java11:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/composite-build
        with:
          JAVA_VERSION: 11

  build-java12:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/composite-build
        with:
          JAVA_VERSION: 12

  build-java13:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/composite-build
        with:
          JAVA_VERSION: 13

  build-java14:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/composite-build
        with:
          JAVA_VERSION: 14

  build-java15:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/composite-build
        with:
          JAVA_VERSION: 15

  build-java16:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/composite-build
        with:
          JAVA_VERSION: 16

  build-java17:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/composite-build
        with:
          JAVA_VERSION: 17