name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  skipci:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build-java17:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Set up Java17'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Build Herts project with Java17'
        run: |
          ./gradlew clean build -P javaVersion=17
          cat herts-common/build/tmp/jar/MANIFEST.MF

  build-java16:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Set up Java16'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '16'

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Build Herts project with Java16'
        run: |
          ./gradlew clean build -P javaVersion=16
          cat herts-common/build/tmp/jar/MANIFEST.MF

  build-java11:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Set up Java11'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Build Herts project with Java11'
        run: |
          ./gradlew clean build -P javaVersion=11
          cat herts-common/build/tmp/jar/MANIFEST.MF

  build-java8:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Set up Java8'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Build Herts project with Java8'
        run: |
          ./gradlew clean build -P javaVersion=8
          cat herts-common/build/tmp/jar/MANIFEST.MF
