name: "Release"
on:
  push:
    tags:
      - herts-rpc-v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/composite-release
        with:
          JAVA_VERSION: 11
          HERTS_PKG_NAME: 'herts-rpc'
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          KEY: ${{ secrets.KEY }}
          GRADLE_PROP: ${{ secrets.GRADLE_PROP }}
