name: "Release"
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      pkg_namw: ${{ steps.findpkg.outputs.pkg_name }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set env'
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: 'Find package name on tag'
        shell: bash
        id: findpkg
        run: |
          pkg_name_with_h=`echo ${{ env.RELEASE_VERSION }} | tr "v" "\n" | head -n 1`
          pkg_name=`echo ${pkg_name_with_h%?}`
          echo "pkg_name=$pkg_name" >> $GITHUB_OUTPUT

      - uses: ./.github/composite-release
        with:
          JAVA_VERSION: 15
          HERTS_PKG_NAME: ${{ steps.findpkg.outputs.pkg_name }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          KEY: ${{ secrets.KEY }}
          GRADLE_PROP: ${{ secrets.GRADLE_PROP }}
