name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  end-2-end-java11:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/composite-test
        with:
          JAVA_VERSION: 11

  end-2-end-java12:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java12'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'End 2 End test with Java12'
        shell: bash
        run: |
          gradle wrapper
          ./e2e-test/test.sh 12

  end-2-end-java13:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java13'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '13'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'End 2 End test with Java13'
        shell: bash
        run: |
          gradle wrapper
          ./e2e-test/test.sh 13

  end-2-end-java14:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java14'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '14'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'End 2 End test with Java14'
        shell: bash
        run: |
          gradle wrapper
          ./e2e-test/test.sh 14

  end-2-end-java15:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java15'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '15'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'End 2 End test with Java15'
        shell: bash
        run: |
          gradle wrapper
          ./e2e-test/test.sh 15

  end-2-end-java16:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java16'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '16'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'End 2 End test with Java16'
        shell: bash
        run: |
          gradle wrapper
          ./e2e-test/test.sh 16

  end-2-end-java17:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}
    steps:
      - name: 'Set up Java17'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'End 2 End test with Java17'
        shell: bash
        run: |
          gradle wrapper
          ./e2e-test/test.sh 17